config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def landing_page
    @featured_product = Product.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>Nameofapp</title>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">


	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>


	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= csrf_meta_tags %>

  </head>

  <body>

<!--============ NAV TOP BAR ============-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid container-fluid-nav">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <div id="logo" class="navbar-brand">
            <span class="nav-logo">Veneto Bird Tours</span>
          </div>
        </div><!-- /navbar-header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
        </div><!-- /navbar collapse -->
      </div><!-- /container-fluid -->
    </nav><!-- /nav -->




	<%= yield %>

<!--============ FOOTER BOTTOM BAR ============-->
	<footer class="footer">
	<p>The date and time is <%= Time.now %> &copy; 2017 Lisa Leung </p>
	</footer>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="field">
    <%= form.label :colour %><br>
    <%= form.text_field :colour %>
  </div>

  <div class="price">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>



<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-2 col-md-4">
        <% if product.image_url %>
          <%= image_tag(product.image_url, class: "img-responsive") %>
        <% end %>
        <a href="#"><h1><%= product.name %></h1></a>
        <p><%= product.description %></p>
        <p><%= product.price %></p>
        <strong>$ 100</strong>
      </div><!-- /col -->
    <% end %>
  </div>
</div>




<table>
<!--   <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> 

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<div class="page-container">


<div class="container-fluid my-section space about-me" id="about">
  
    <div class="header">
      <h1>About Veneto Bird Tours</h1>
      <br>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3  photo-lisa">
          <div class="column">
          	<%= image_tag("birder.jpg") %>
          </div>
        </div><!-- /col -->
        
        <div class="col-xs-12 col-sm-8 col-md-9">
						<p>Veneto Bird Tours is run by Lisa Leung, a Canadian birder who has worked for the North American Bird Breeding Atlas, the Toronto Zoo (as the Bird Conservation Technician) and a bird tour operator in Okinawa, Japan. She has moved around the world chasing birds since 2005. Her favorite places to bird have been Thailand, Swaziland, South Africa, Costa Rica, Mexico, Hong Kong, Australia and Spain.</p>
						<p>Depending on your location, how much time you have, how athletic you are, and your target bird species list, Lisa can cater your tour to suit your exact needs.</p>
						<p>If you would like a specialized tour, please contact Veneto Bird Tours to discuss your options.</p>
        </div><!-- /col -->
      </div> <!-- /row -->	
    </div><!-- /container -->
</div> <!-- /container-fluid -->

</div> <!-- /page-container -->

app/views/simple_pages/contact.html.erb
<div class="page-container">

<h1>Contact Veneto Bird Tours</h1>

	<div class="table-contact">
		<form>

      <div class="form-group" class="form-control contact-form" required="required">
        <label for="Name">*Your name:</label>
        <br>
        <input type="name" placeholder="*Enter your name." id="Name" title="Please enter your full name.">
      </div>

      <div class="form-group" class="form-control contact-form" required="required">
        <label for="Email">Email address:</label>
        <br>
        <input type="text" placeholder="Enter your email." id="Email">
      </div>

      <div class="form-group" class="form-control contact-form" required="required">
        <label for="Location">Where you are staying:</label>
        <br>
        <input type="name" placeholder="*Enter pickup location." id="Name" title="Please enter your location.">
      </div>

      <div class="form-group">
        <label for="Message">*Your message:</label><br>
        <textarea style="resize:none" cols="40" rows="5" placeholder="Type your message here." class="message-box contact-form" id="Message" required="required" title="Please enter your question, comment or message here."></textarea>
        <p id="visible-comment"></p>
      </div>
      <br>

      <div class="btn-space">
      	<button type="submit" class="btn btn-primary" id="button" data-toggle="tooltip" data-placement="top" title="Submit your request.">Submit</button>  
      </div>      

		</form>
	</div><!-- /table-contact -->
</div> <!-- /page-container -->

app/views/simple_pages/index.html.erb
<div class="page-container">


<h1>Welcome to Veneto Bird Tours</h1>


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("venice.jpg") %>
      <div class="carousel-caption">
          <h3>Venice</h3>
          <p>Often overlooked, Venice offers a unique and easy-to-tick birds.</p>
          
      </div>
    </div>
    <div class="item">
      <%= image_tag("podelta.jpg") %>
      <div class="carousel-caption">
          <h3>Po Delta</h3>
          <p>The Po Delta has the best wetlands in Northern Italy.</p>
         
      </div>
    </div>
    <div class="item">
      <%= image_tag("dolomites.jpg") %>
      <div class="carousel-caption">
          <h3>The Dolomites</h3>
          <p>Weather permitting, the Dolomite Mountains offer an extensive range of alpine species.</p>
        
      </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- end carousel-example-generic -->


  </div> <!-- end container-fluid index -->









<div class="intro-container">
	<div class="table-intro">
		<p>Veneto has some of the best birding in Italy. Whether you want to explore farmlands, cities, wetlands or mountains, the Veneto region has more birds by volume and diversity than anywhere else in the country. Whether you have a week, a day or just a morning, Veneto Bird Tours can cater to your needs to help you tick your list quickly and efficiently so that you can enjoy the rest of your time in the region.</p>
	</div>
</div>

</div> <!-- /page-container -->

app/views/simple_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<%= @featured_product.name %>